<?php
$data = array (
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '韩国NEO VISION系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '23',
    'goods_num' => 0,
    'level' => 0,
    'id' => '59',
    'name' => '韩国NEO VISION系列',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => 'NEO巨目迷光',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '144',
    'name' => 'NEO巨目迷光',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => 'NEO天使三色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '64',
    'name' => 'NEO天使三色',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => 'NEO幸运四色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '141',
    'name' => 'NEO幸运四色',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => 'NEO暮色榛仁',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '162',
    'name' => 'NEO暮色榛仁',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => 'NEO冰凌系列',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '261',
    'name' => 'NEO冰凌系列',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => 'NEO新之目',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '157',
    'name' => 'NEO新之目',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => 'NEO丝光系列',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '268',
    'name' => 'NEO丝光系列',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'NEO日抛&周抛',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '223',
    'name' => 'NEO日抛&周抛',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => 'NEO巧克力',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '151',
    'name' => 'NEO巧克力',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => 'NEO Heart心语',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '145',
    'name' => 'NEO Heart心语',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => 'NEO巨目四代',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '276',
    'name' => 'NEO巨目四代',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => 'NEO巨目双色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '142',
    'name' => 'NEO巨目双色',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => 'NEO混血自然',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '272',
    'name' => 'NEO混血自然',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => 'NEO舒娜丝滑',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '160',
    'name' => 'NEO舒娜丝滑',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'NEO孔雀三色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '155',
    'name' => 'NEO孔雀三色',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'NEO Monet自然',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '149',
    'name' => 'NEO Monet自然',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => 'NEO钻石双色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '146',
    'name' => 'NEO钻石双色',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => 'NEO巨目微光',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '143',
    'name' => 'NEO巨目微光',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => 'NEO女皇四色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '140',
    'name' => 'NEO女皇四色',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => 'NEO八芒星',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '161',
    'name' => 'NEO八芒星',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => 'NEO公主三色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '156',
    'name' => 'NEO公主三色',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => 'NEO玫瑰&黑环',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '150',
    'name' => 'NEO玫瑰&黑环',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => 'NEO果冻系列',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '159',
    'name' => 'NEO果冻系列',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '韩国GEO Medical',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '61',
    'name' => '韩国GEO Medical',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => 'GEO Grang奶茶',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '70',
    'name' => 'GEO Grang奶茶',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'Prime Bambi',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '68',
    'name' => 'Prime Bambi',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => 'GEO XTRA女神',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '73',
    'name' => 'GEO XTRA女神',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'GEO Marii金粉',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '71',
    'name' => 'GEO Marii金粉',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'GEO Cafe咖啡',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '69',
    'name' => 'GEO Cafe咖啡',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'GEO Starimsh',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '216',
    'name' => 'GEO Starimsh',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'GEO惑丽猫Ⅱ代',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '65',
    'name' => 'GEO惑丽猫Ⅱ代',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => 'GEO水凝系列',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '267',
    'name' => 'GEO水凝系列',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'GEO奶油三色',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '67',
    'name' => 'GEO奶油三色',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => 'GEO混血三色',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '72',
    'name' => 'GEO混血三色',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '韩国BESCON Business',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '97',
    'name' => '韩国BESCON Business',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => 'BESCON甜心双色',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '209',
    'name' => 'BESCON甜心双色',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => 'BESCON双色钻石',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '210',
    'name' => 'BESCON双色钻石',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => 'BESCON Tutti三色',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '206',
    'name' => 'BESCON Tutti三色',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => 'BESCON炫彩三色',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '258',
    'name' => 'BESCON炫彩三色',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => 'BESCON七代润彩',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '211',
    'name' => 'BESCON七代润彩',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => 'BESCON自然系列',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '208',
    'name' => 'BESCON自然系列',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => 'BESCON热销',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '264',
    'name' => 'BESCON热销',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => 'BESCON Classic',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 5,
    'level' => 1,
    'id' => '260',
    'name' => 'BESCON Classic',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => 'BESCON Cir梦幻',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '259',
    'name' => 'BESCON Cir梦幻',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '韩国DUEBA ContactLens',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '62',
    'name' => '韩国DUEBA ContactLens',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => 'DUEBA Very三色',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '203',
    'name' => 'DUEBA Very三色',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => 'DUEBA大露珠',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '200',
    'name' => 'DUEBA大露珠',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => 'DUEBA深咖啡',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '197',
    'name' => 'DUEBA深咖啡',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => 'DUEBA阳光少女',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '201',
    'name' => 'DUEBA阳光少女',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => 'DUEBA珍珠黑',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '198',
    'name' => 'DUEBA珍珠黑',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => 'DUEBA思诺女皇',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '202',
    'name' => 'DUEBA思诺女皇',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => 'DUEBA神秘黑',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '199',
    'name' => 'DUEBA神秘黑',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => 'DUEBA巧克力',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '196',
    'name' => 'DUEBA巧克力',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '韩国EOS Contactlens',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '78',
    'name' => '韩国EOS Contactlens',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => 'EOS 101-Dark',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '213',
    'name' => 'EOS 101-Dark',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'Dark ice暗冰',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '214',
    'name' => 'Dark ice暗冰',
  ),
  277 => 
  array (
    'cat_id' => '277',
    'cat_name' => 'Tearly猫目泪花',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '277',
    'name' => 'Tearly猫目泪花',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => 'EOS Peach冰润',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '271',
    'name' => 'EOS Peach冰润',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => 'ICE冰润雪花',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '215',
    'name' => 'ICE冰润雪花',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'EOS幸运三色',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '212',
    'name' => 'EOS幸运三色',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '精品·眸敦7Modern',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '91',
    'name' => '精品·眸敦7Modern',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '7Modern唐纳滋',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '170',
    'name' => '7Modern唐纳滋',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '7Modern雪莉双色',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '174',
    'name' => '7Modern雪莉双色',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '7Modern琥珀四色',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '171',
    'name' => '7Modern琥珀四色',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '7MODERN巧克力Ⅱ代',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '175',
    'name' => '7MODERN巧克力Ⅱ代',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '7Modern花漾甜心',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '172',
    'name' => '7Modern花漾甜心',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '7Modern巧克力多',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '173',
    'name' => '7Modern巧克力多',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '韩国DREAMCON Tact',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '118',
    'name' => '韩国DREAMCON Tact',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'BLOOM双色系列',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '231',
    'name' => 'BLOOM双色系列',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => 'DREAMCON卡布基诺',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '232',
    'name' => 'DREAMCON卡布基诺',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => 'GOLDEN千金小姐',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '228',
    'name' => 'GOLDEN千金小姐',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'COLORPIA三色',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '227',
    'name' => 'COLORPIA三色',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'DREAMCON下午茶',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '229',
    'name' => 'DREAMCON下午茶',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => 'DREAMCON Atti系列',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '266',
    'name' => 'DREAMCON Atti系列',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => 'DREAMCON伯爵茶',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '230',
    'name' => 'DREAMCON伯爵茶',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '韩国MIMO Lens系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '112',
    'name' => '韩国MIMO Lens系列',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => 'Mimo Elly新品季抛',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '221',
    'name' => 'Mimo Elly新品季抛',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => 'Mimo Classic月抛',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '222',
    'name' => 'Mimo Classic月抛',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'Mimo钻石甜心系列',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '220',
    'name' => 'Mimo钻石甜心系列',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '宝贝色BABY-COLOR',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 0,
    'id' => '110',
    'name' => '宝贝色BABY-COLOR',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => 'Babycolr人气棕',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '190',
    'name' => 'Babycolr人气棕',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => 'Babycolr恶魔宝贝',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '187',
    'name' => 'Babycolr恶魔宝贝',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => 'Babycolr大优格',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '194',
    'name' => 'Babycolr大优格',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => 'Babycolr哈咯蜜',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '191',
    'name' => 'Babycolr哈咯蜜',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => 'Babycolr摩卡宝贝',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '188',
    'name' => 'Babycolr摩卡宝贝',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => 'Babycolr迷萌系列',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '195',
    'name' => 'Babycolr迷萌系列',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => 'Babycolr可可小姐',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '192',
    'name' => 'Babycolr可可小姐',
  ),
  185 => 
  array (
    'cat_id' => '185',
    'cat_name' => 'Babycolr大钻石',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '185',
    'name' => 'Babycolr大钻石',
  ),
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => 'Babycolr大萝莉',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '189',
    'name' => 'Babycolr大萝莉',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => 'Babycolr彩虹糖',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '186',
    'name' => 'Babycolr彩虹糖',
  ),
  193 => 
  array (
    'cat_id' => '193',
    'cat_name' => 'Babycolr混血女神',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '193',
    'name' => 'Babycolr混血女神',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '韩国-福森(VASSEN)系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '99',
    'name' => '韩国-福森(VASSEN)系列',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => 'Vassen菠萝四色',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '179',
    'name' => 'Vassen菠萝四色',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => 'Vassen七色大美目',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '176',
    'name' => 'Vassen七色大美目',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '米欧米MIOMI(原芭比爱)',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '111',
    'name' => '米欧米MIOMI(原芭比爱)',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => 'MIOMI E·T极光',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '233',
    'name' => 'MIOMI E·T极光',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => 'MIOMI蕾丝公主',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '234',
    'name' => 'MIOMI蕾丝公主',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => 'MIOMI琪克力',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '239',
    'name' => 'MIOMI琪克力',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => 'MIOMI芭比幻影',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '236',
    'name' => 'MIOMI芭比幻影',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => 'MIOMI七彩钻石',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '235',
    'name' => 'MIOMI七彩钻石',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'MIOMI大水凝',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '237',
    'name' => 'MIOMI大水凝',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '微眸VIIMON(原VIVIAN)',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '247',
    'name' => '微眸VIIMON(原VIVIAN)',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'VIVIAN菠萝三色',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '248',
    'name' => 'VIVIAN菠萝三色',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => 'VIVIAN花嫁三色',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '249',
    'name' => 'VIVIAN花嫁三色',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '其它热卖品牌',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '6',
    'goods_num' => '1',
    'level' => 0,
    'id' => '6',
    'name' => '其它热卖品牌',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => 'Cosplay写轮眼',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '269',
    'name' => 'Cosplay写轮眼',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => 'Peggy佩吉四色系',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '183',
    'name' => 'Peggy佩吉四色系',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => 'AMBSEE倾心三色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '244',
    'name' => 'AMBSEE倾心三色',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => 'FORTUNE巧克力',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '217',
    'name' => 'FORTUNE巧克力',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => 'Cupcake蛋糕四色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '184',
    'name' => 'Cupcake蛋糕四色',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => 'CICI熙爱米克斯',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '246',
    'name' => 'CICI熙爱米克斯',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '护理产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 0,
    'id' => '75',
    'name' => '护理产品',
  ),
  224 => 
  array (
    'cat_id' => '224',
    'cat_name' => '滴眼液',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '224',
    'name' => '滴眼液',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => '护理液',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '225',
    'name' => '护理液',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '洗眼液',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '226',
    'name' => '洗眼液',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '高端品牌-日本Aevecon',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '273',
    'name' => '高端品牌-日本Aevecon',
  ),
  275 => 
  array (
    'cat_id' => '275',
    'cat_name' => 'Foam泡沫单色',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '275',
    'name' => 'Foam泡沫单色',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => 'Rinka梨花四色',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '274',
    'name' => 'Rinka梨花四色',
  ),
);
?>