<?php
$data = array (
  0 => 
  array (
    'cat_id' => '59',
    'cat_name' => '韩国NEO VISION系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '23',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '61',
    'cat_name' => '韩国GEO Medical',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '97',
    'cat_name' => '韩国BESCON Business',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '62',
    'cat_name' => '韩国DUEBA ContactLens',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '78',
    'cat_name' => '韩国EOS Contactlens',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '91',
    'cat_name' => '精品·眸敦7Modern',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '118',
    'cat_name' => '韩国DREAMCON Tact',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '112',
    'cat_name' => '韩国MIMO Lens系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '110',
    'cat_name' => '宝贝色BABY-COLOR',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '11',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '99',
    'cat_name' => '韩国-福森(VASSEN)系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '111',
    'cat_name' => '米欧米MIOMI(原芭比爱)',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '247',
    'cat_name' => '微眸VIIMON(原VIVIAN)',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '6',
    'cat_name' => '其它热卖品牌',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '6',
    'goods_num' => '1',
  ),
  13 => 
  array (
    'cat_id' => '75',
    'cat_name' => '护理产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '3',
    'goods_num' => '1',
  ),
  14 => 
  array (
    'cat_id' => '273',
    'cat_name' => '高端品牌-日本Aevecon',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '269',
    'cat_name' => 'Cosplay写轮眼',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  16 => 
  array (
    'cat_id' => '183',
    'cat_name' => 'Peggy佩吉四色系',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  17 => 
  array (
    'cat_id' => '244',
    'cat_name' => 'AMBSEE倾心三色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  18 => 
  array (
    'cat_id' => '217',
    'cat_name' => 'FORTUNE巧克力',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  19 => 
  array (
    'cat_id' => '184',
    'cat_name' => 'Cupcake蛋糕四色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  20 => 
  array (
    'cat_id' => '246',
    'cat_name' => 'CICI熙爱米克斯',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  21 => 
  array (
    'cat_id' => '157',
    'cat_name' => 'NEO新之目',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  22 => 
  array (
    'cat_id' => '268',
    'cat_name' => 'NEO丝光系列',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  23 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'NEO日抛&周抛',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  24 => 
  array (
    'cat_id' => '151',
    'cat_name' => 'NEO巧克力',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  25 => 
  array (
    'cat_id' => '145',
    'cat_name' => 'NEO Heart心语',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  26 => 
  array (
    'cat_id' => '276',
    'cat_name' => 'NEO巨目四代',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  27 => 
  array (
    'cat_id' => '142',
    'cat_name' => 'NEO巨目双色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  28 => 
  array (
    'cat_id' => '272',
    'cat_name' => 'NEO混血自然',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  29 => 
  array (
    'cat_id' => '160',
    'cat_name' => 'NEO舒娜丝滑',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  30 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'NEO孔雀三色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  31 => 
  array (
    'cat_id' => '149',
    'cat_name' => 'NEO Monet自然',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  32 => 
  array (
    'cat_id' => '146',
    'cat_name' => 'NEO钻石双色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  33 => 
  array (
    'cat_id' => '143',
    'cat_name' => 'NEO巨目微光',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  34 => 
  array (
    'cat_id' => '140',
    'cat_name' => 'NEO女皇四色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  35 => 
  array (
    'cat_id' => '161',
    'cat_name' => 'NEO八芒星',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  36 => 
  array (
    'cat_id' => '156',
    'cat_name' => 'NEO公主三色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  37 => 
  array (
    'cat_id' => '150',
    'cat_name' => 'NEO玫瑰&黑环',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  38 => 
  array (
    'cat_id' => '159',
    'cat_name' => 'NEO果冻系列',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  39 => 
  array (
    'cat_id' => '144',
    'cat_name' => 'NEO巨目迷光',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  40 => 
  array (
    'cat_id' => '64',
    'cat_name' => 'NEO天使三色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  41 => 
  array (
    'cat_id' => '141',
    'cat_name' => 'NEO幸运四色',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  42 => 
  array (
    'cat_id' => '162',
    'cat_name' => 'NEO暮色榛仁',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  43 => 
  array (
    'cat_id' => '261',
    'cat_name' => 'NEO冰凌系列',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  44 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'GEO Cafe咖啡',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  45 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'GEO Starimsh',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  46 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'GEO Marii金粉',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  47 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'GEO惑丽猫Ⅱ代',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  48 => 
  array (
    'cat_id' => '267',
    'cat_name' => 'GEO水凝系列',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  49 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'GEO奶油三色',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  50 => 
  array (
    'cat_id' => '72',
    'cat_name' => 'GEO混血三色',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  51 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'Prime Bambi',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  52 => 
  array (
    'cat_id' => '70',
    'cat_name' => 'GEO Grang奶茶',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  53 => 
  array (
    'cat_id' => '73',
    'cat_name' => 'GEO XTRA女神',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  54 => 
  array (
    'cat_id' => '200',
    'cat_name' => 'DUEBA大露珠',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  55 => 
  array (
    'cat_id' => '197',
    'cat_name' => 'DUEBA深咖啡',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  56 => 
  array (
    'cat_id' => '201',
    'cat_name' => 'DUEBA阳光少女',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  57 => 
  array (
    'cat_id' => '198',
    'cat_name' => 'DUEBA珍珠黑',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  58 => 
  array (
    'cat_id' => '202',
    'cat_name' => 'DUEBA思诺女皇',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  59 => 
  array (
    'cat_id' => '199',
    'cat_name' => 'DUEBA神秘黑',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '196',
    'cat_name' => 'DUEBA巧克力',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  61 => 
  array (
    'cat_id' => '203',
    'cat_name' => 'DUEBA Very三色',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  62 => 
  array (
    'cat_id' => '224',
    'cat_name' => '滴眼液',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  63 => 
  array (
    'cat_id' => '225',
    'cat_name' => '护理液',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  64 => 
  array (
    'cat_id' => '226',
    'cat_name' => '洗眼液',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  65 => 
  array (
    'cat_id' => '213',
    'cat_name' => 'EOS 101-Dark',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  66 => 
  array (
    'cat_id' => '214',
    'cat_name' => 'Dark ice暗冰',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  67 => 
  array (
    'cat_id' => '277',
    'cat_name' => 'Tearly猫目泪花',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '271',
    'cat_name' => 'EOS Peach冰润',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  69 => 
  array (
    'cat_id' => '215',
    'cat_name' => 'ICE冰润雪花',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  70 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'EOS幸运三色',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  71 => 
  array (
    'cat_id' => '174',
    'cat_name' => '7Modern雪莉双色',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  72 => 
  array (
    'cat_id' => '171',
    'cat_name' => '7Modern琥珀四色',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  73 => 
  array (
    'cat_id' => '175',
    'cat_name' => '7MODERN巧克力Ⅱ代',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  74 => 
  array (
    'cat_id' => '172',
    'cat_name' => '7Modern花漾甜心',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  75 => 
  array (
    'cat_id' => '173',
    'cat_name' => '7Modern巧克力多',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  76 => 
  array (
    'cat_id' => '170',
    'cat_name' => '7Modern唐纳滋',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  77 => 
  array (
    'cat_id' => '210',
    'cat_name' => 'BESCON双色钻石',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  78 => 
  array (
    'cat_id' => '206',
    'cat_name' => 'BESCON Tutti三色',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  79 => 
  array (
    'cat_id' => '258',
    'cat_name' => 'BESCON炫彩三色',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  80 => 
  array (
    'cat_id' => '211',
    'cat_name' => 'BESCON七代润彩',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  81 => 
  array (
    'cat_id' => '208',
    'cat_name' => 'BESCON自然系列',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  82 => 
  array (
    'cat_id' => '264',
    'cat_name' => 'BESCON热销',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '260',
    'cat_name' => 'BESCON Classic',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 5,
  ),
  84 => 
  array (
    'cat_id' => '259',
    'cat_name' => 'BESCON Cir梦幻',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  85 => 
  array (
    'cat_id' => '209',
    'cat_name' => 'BESCON甜心双色',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  86 => 
  array (
    'cat_id' => '179',
    'cat_name' => 'Vassen菠萝四色',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  87 => 
  array (
    'cat_id' => '176',
    'cat_name' => 'Vassen七色大美目',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  88 => 
  array (
    'cat_id' => '194',
    'cat_name' => 'Babycolr大优格',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  89 => 
  array (
    'cat_id' => '191',
    'cat_name' => 'Babycolr哈咯蜜',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  90 => 
  array (
    'cat_id' => '188',
    'cat_name' => 'Babycolr摩卡宝贝',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '195',
    'cat_name' => 'Babycolr迷萌系列',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  92 => 
  array (
    'cat_id' => '192',
    'cat_name' => 'Babycolr可可小姐',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  93 => 
  array (
    'cat_id' => '185',
    'cat_name' => 'Babycolr大钻石',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  94 => 
  array (
    'cat_id' => '189',
    'cat_name' => 'Babycolr大萝莉',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  95 => 
  array (
    'cat_id' => '186',
    'cat_name' => 'Babycolr彩虹糖',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  96 => 
  array (
    'cat_id' => '193',
    'cat_name' => 'Babycolr混血女神',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  97 => 
  array (
    'cat_id' => '190',
    'cat_name' => 'Babycolr人气棕',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '187',
    'cat_name' => 'Babycolr恶魔宝贝',
    'measure_unit' => '',
    'parent_id' => '110',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  99 => 
  array (
    'cat_id' => '233',
    'cat_name' => 'MIOMI E·T极光',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  100 => 
  array (
    'cat_id' => '234',
    'cat_name' => 'MIOMI蕾丝公主',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  101 => 
  array (
    'cat_id' => '239',
    'cat_name' => 'MIOMI琪克力',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  102 => 
  array (
    'cat_id' => '236',
    'cat_name' => 'MIOMI芭比幻影',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  103 => 
  array (
    'cat_id' => '235',
    'cat_name' => 'MIOMI七彩钻石',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  104 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'MIOMI大水凝',
    'measure_unit' => '',
    'parent_id' => '111',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  105 => 
  array (
    'cat_id' => '221',
    'cat_name' => 'Mimo Elly新品季抛',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  106 => 
  array (
    'cat_id' => '222',
    'cat_name' => 'Mimo Classic月抛',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  107 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'Mimo钻石甜心系列',
    'measure_unit' => '',
    'parent_id' => '112',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  108 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'BLOOM双色系列',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  109 => 
  array (
    'cat_id' => '232',
    'cat_name' => 'DREAMCON卡布基诺',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  110 => 
  array (
    'cat_id' => '228',
    'cat_name' => 'GOLDEN千金小姐',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  111 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'COLORPIA三色',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  112 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'DREAMCON下午茶',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  113 => 
  array (
    'cat_id' => '266',
    'cat_name' => 'DREAMCON Atti系列',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  114 => 
  array (
    'cat_id' => '230',
    'cat_name' => 'DREAMCON伯爵茶',
    'measure_unit' => '',
    'parent_id' => '118',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  115 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'VIVIAN菠萝三色',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  116 => 
  array (
    'cat_id' => '249',
    'cat_name' => 'VIVIAN花嫁三色',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  117 => 
  array (
    'cat_id' => '274',
    'cat_name' => 'Rinka梨花四色',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  118 => 
  array (
    'cat_id' => '275',
    'cat_name' => 'Foam泡沫单色',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
);
?>